.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.TH FILESPECTOR 1 "21 April 2018" "" "User Manual"

.SH NAME
filespector \- Find text occurrences in multiple files

.SH SYNOPSIS
.B filespector
.br

.SH DESCRIPTION
FileSpector is a GUI tool for quickly finding all text occurrences in multiple
files in a directory, matching a specific file extension pattern.
